#!/bin/bash

file_name="${1##*/}"
file_extension="${file_name##*.}"
file="${file_name%.*}"
out="/tmp/${file}_$(date +"%Y-%m-%d").pdf"
# -H ~/.local/share/pandoc/headers/chapter_break.tex \
#-H ~/.local/share/pandoc/headers/syntax_highlight.tex \
pandoc "$1" \
  -f markdown \
  --toc -N \
  -V colorlinks -V urlcolor=NavyBlue \
  -H ~/.local/share/pandoc/headers/bullet_list.tex \
  -H ~/.local/share/pandoc/headers/deeplist.tex \
  -F mermaid-filter \
  -V geometry:a4paper \
  -V geometry:"top=2cm, bottom=1.5cm, left=2cm, right=2cm" \
  -V mainfont="DejaVu Serif" \
  -V monofont="DejaVu Sans Mono" \
  --pdf-engine=xelatex \
  --template=gitbook-azure.tex \
  -o "${out}"
echo "created pdf at ${out}"

xdg-open "${out}"
