---
- name: Ensure ~/.ssh directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'

- name: Link ssh config file
  ansible.builtin.file:
    src: "{{ role_path }}/files/config"
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    state: link
    force: true
    mode: '0600'

- name: Generate SSH key if it doesn't exist
  community.crypto.openssh_keypair:
    path: "{{ ansible_env.HOME }}/.ssh/id_ed25519_priv"
    type: rsa
    size: 4096
    state: present
