---
- stat: path={{ ansible_env.HOME }}/.local/share/fonts/Hack-Regular.ttf
  register: hack_font_check

- block:

  - name: make font dir
    file: path={{ ansible_env.HOME }}/.local/share/fonts/ state=directory

  - name: checkout hack-font repo
    git: >
      repo=https://github.com/powerline/fonts.git
      dest=/tmp/hackfont
      accept_hostkey=yes
      force=yes
    ignore_errors: yes

  - name: install font
    shell: /tmp/hackfont/install.sh

  - name: cleanup font
    file: path=/tmp/hackfont/ state=absent

  when: hack_font_check.stat.exists == False



- stat: path={{ ansible_env.HOME }}/.local/share/fonts/FiraCode-Regular.ttf
  register: firacode_font_check

- block:

  - name: make font dir
    file: path={{ ansible_env.HOME }}/.local/share/fonts/ state=directory

  - name: make tmp dir
    file: path=/tmp/FiraCode/ state=directory


  - name: Download and unarchive
    unarchive:
      src: https://github.com/tonsky/FiraCode/releases/download/{{ firacode_version }}/Fira_Code_v{{ firacode_version }}.zip
      dest: /tmp/FiraCode
      remote_src: yes

  - name: Move directory contents
    command: cp -r /tmp/FiraCode/ttf/. {{ ansible_env.HOME }}/.local/share/fonts/

  when: firacode_font_check.stat.exists == False
