---
- name: Initialize font_installed flag
  set_fact:
    font_installed: false

- name: Check if Hack font is installed
  stat:
    path: "{{ ansible_env.HOME }}/.local/share/fonts/Hack-Regular.ttf"
  register: hack_font_check

- name: Install Hack font
  block:
    - name: Create font directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/share/fonts"
        state: directory
        mode: '0755'

    - name: Clone Hack font repository
      ansible.builtin.git:
        repo: https://github.com/source-foundry/Hack.git
        dest: /tmp/hackfont
        version: "{{ hack_font_version }}"
        accept_hostkey: true

    - name: Install Hack font
      ansible.builtin.shell: /tmp/hackfont/install.sh

    - name: Clean up Hack font repository
      ansible.builtin.file:
        path: /tmp/hackfont
        state: absent

    - name: Set font_installed flag
      set_fact:
        font_installed: true
  when: not hack_font_check.stat.exists

- name: Check if Fira Code font is installed
  stat:
    path: "{{ ansible_env.HOME }}/.local/share/fonts/FiraCode-Regular.ttf"
  register: firacode_font_check

- name: Install Fira Code font
  block:
    - name: Create font directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/share/fonts"
        state: directory
        mode: '0755'

    - name: Download and unarchive Fira Code font
      ansible.builtin.unarchive:
        src: "https://github.com/tonsky/FiraCode/releases/download/{{ firacode_version }}/Fira_Code_v{{ firacode_version }}.zip"
        dest: "{{ ansible_env.HOME }}/.local/share/fonts"
        remote_src: true
        creates: "{{ ansible_env.HOME }}/.local/share/fonts/FiraCode-Regular.ttf"

    - name: Set font_installed flag
      set_fact:
        font_installed: true
  when: not firacode_font_check.stat.exists

- name: Update font cache
  ansible.builtin.command: fc-cache -f -v
  changed_when: false
  when: font_installed
