ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

[rule.atomic]
[rule.blank-imports]
[rule.bool-literal-in-expr]
[rule.context-as-argument]
[rule.constant-logical-expr]
[rule.cyclomatic]
  arguments =[10]
[rule.context-keys-type]
[rule.dot-imports]
[rule.empty-block]
[rule.empty-lines]
[rule.error-naming]
[rule.error-return]
[rule.error-strings]
[rule.errorf]
[rule.flag-parameter]
[rule.if-return]
[rule.increment-decrement]
[rule.indent-error-flow]
[rule.import-shadowing]
[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.redefines-builtin-id]
[rule.superfluous-else]
[rule.time-naming]
[rule.unexported-return]
[rule.unreachable-code]
[rule.unused-parameter]
[rule.unused-receiver]
[rule.unhandled-error]
[rule.unnecessary-stmt]
[rule.var-declaration]
[rule.var-naming]
[rule.waitgroup-by-value]
