---

- name: Configure git
  community.general.git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - { name: 'init.templatedir', value: '~/.git_templates' }
    - { name: 'core.excludesfile', value: '~/.gitignore' }
    - { name: 'alias.ri', value: 'rebase --interactive --autosquash' }
    - { name: 'pull.rebase', value: 'true' }
    - { name: 'fetch.prune', value: 'true' }
    - { name: 'rebase.autoStash', value: 'true' }
    - { name: 'rerere.enabled', value: 'false' }
    - { name: 'rerere.autoupdate', value: 'false' }
    - { name: 'advice.statusHints', value: 'false' }
    - { name: 'diff.algorithm', value: 'histogram' }
    - { name: 'diff.renames', value: 'copies' }
    - { name: 'diff.mnemonicprefix', value: 'true' }
    - { name: 'url.diff.whitespace', value: 'red reverse' }
    - { name: 'diff.tool', value: 'nvimdiff' }
    - { name: 'difftool.prompt', value: 'false' }
    - { name: 'difftool.trustExitCode', value: 'true' }
    - { name: 'merge.tool', value: 'diffconflicts' }
    - { name: 'mergetool.prompt', value: 'false' }
    - { name: 'mergetool.keepBackup', value: 'false' }
    - { name: 'commit.verbose', value: 'true' }
    - { name: 'color.ui', value: 'true' }
    - { name: 'color.diff-highlight.oldNormal', value: 'red bold' }
    - { name: 'color.diff-highlight.oldHighlight', value: 'red bold 52' }
    - { name: 'color.diff-highlight.newNormal', value: 'green bold' }
    - { name: 'color.diff-highlight.newHighlight', value: 'green bold 22' }
    - { name: 'color.diff.meta', value: 'yellow' }
    - { name: 'color.diff.frag', value: 'magenta bold' }
    - { name: 'color.diff.commit', value: 'yellow bold' }
    - { name: 'color.diff.old', value: 'red bold' }
    - { name: 'color.diff.new', value: 'green bold' }
    - { name: 'color.diff.whitespace', value: 'red reverse' }