---

- name: check to see if diff-so-fancy is already installed
  command: "diff-so-fancy --version"
  ignore_errors: true
  register: diff_so_fancy_installed
  changed_when: false

- name: create .local/bin dir
  file: path={{ ansible_env.HOME }}/.local/bin/ state=directory

- name: install diff-so-fancy
  get_url:
    url: https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy
    dest: ~/.local/bin/
    force: yes

- name: make diff-so-fancy executable
  file:
    path: ~/.local/bin/diff-so-fancy
    mode: a+x
    state: file

- git_config:
    name: core.pager
    scope: global
    value: diff-so-fancy | less --tabs=4 -RFX
