---
- name: Install gemini-cli
  npm:
    name: '@google/gemini-cli'
    global: yes
    state: latest

- name: Link gemini-cli settings
  file:
    src: "{{ role_path }}/files/settings.json"
    dest: "{{ ansible_env.HOME }}/.gemini/settings.json"
    state: link
    force: yes
