vim.api.nvim_set_keymap("n", "<leader>gw", ":Gwrite<cr>", {noremap = true})
vim.api.nvim_set_keymap("n", "<leader>ge", ":Gedit<cr>", {noremap = true})
vim.api.nvim_set_keymap("n", "<leader>gs", ":Gstatus<cr>", {noremap = true})
vim.api.nvim_set_keymap("n", "<leader>gb", ":Gblame<cr>", {noremap = true})
vim.api.nvim_set_keymap("n", "<leader>gc", ":Gcommit -v<cr>", {noremap = true})
vim.api.nvim_set_keymap("n", "<leader>gp", ":Gpush<cr>", {noremap = true})
vim.api.nvim_set_keymap("n", "<leader>gdh", ":Git! difftool<cr>", {noremap = true})
vim.api.nvim_set_keymap("n", "<leader>gds", ":Gdiffsplit<cr>", {noremap = true})
