---
- name: install latest golang
  shell: source ~/.config/zsh/.zshrc && gvm use go1.4 && gvm install {{ go_version }} executable=/bin/zsh

- name: use latest golang
  shell: >
    source ~/.config/zsh/.zshrc &&
    gvm use {{ go_version }} --default executable=/bin/zsh
