---

- name: gvm.yml
  ansible.builtin.import_tasks:
    file: gvm.yml

- name: go1.4.yml
  ansible.builtin.import_tasks:
    file: go1.4.yml

- name: go-latest.yml
  ansible.builtin.import_tasks:
    file: go-latest.yml


- name: linters.yml
  ansible.builtin.import_tasks:
    file: linters.yml

- name: gopls.yml
  ansible.builtin.import_tasks:
    file: gopls.yml


- name: testing.yml
  ansible.builtin.import_tasks:
    file: testing.yml

- name: tools.yml
  ansible.builtin.import_tasks:
    file: tools.yml
