---
- name: check mockery version
  shell: |
    {{ ansible_env.HOME }}/.local/bin/mockery --version 2>&1 | grep -oE 'v?[0-9]+\.[0-9]+\.[0-9]+' || echo 'not found'
  register: mockery_version_check
  changed_when: false

- block:
  - name: get and extract archive
    ansible.builtin.unarchive:
      src: "https://github.com/vektra/mockery/releases/download/{{ go_mockery_version }}/mockery_{{ go_mockery_version | replace('v', '') }}_Linux_x86_64.tar.gz"
      dest: /tmp
      remote_src: yes

  - name: move binary
    ansible.builtin.shell: >
      mv /tmp/mockery {{ ansible_env.HOME }}/.local/bin/ &&
      chmod +x {{ ansible_env.HOME }}/.local/bin/mockery

  when: mockery_version_check.stdout | trim != (go_mockery_version | replace('v', ''))
