---

# - name: Download nix installer
#   get_url:
#     url: https://nixos.org/nix/install
#     dest: /tmp/nixinstaller

# - name: Execute the nixinstaller
#   shell: sh <(curl -L https://nixos.org/nix/install) --no-daemon
