#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
ctags --tag-relative=yes -R -f "$dir/$$.tags" --fields=+aimlS  --PHP-kinds=-va
# ctags --tag-relative -R -f "$dir/$$.tags" --fields=+aimlS --languages=php --PHP-kinds=+cf-va --exclude=var/cache --exclude=vendor/bin --exclude=composer.phar --exclude=web
mv "$dir/$$.tags" "$dir/tags"
