#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags.$1"' EXIT
ctags --tag-relative -R -f "$dir/$$.tags.$1" --fields=+aimlS --languages=$1 --PHP-kinds=+cf-va --exclude=var/cache --exclude=vendor/bin --exclude=*.phar --exclude=web --exclude=assets --exclude=node_modules
mv "$dir/$$.tags.$1" "$dir/tags.$1"
