#!/bin/bash

# Add git branch if relevant
parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

# Extact tracker abbreviation and ticket number (e.g. DS-123)
parse_git_tracker_and_ticket() {
  parse_git_branch | grep -e '[A-Z]\+-[0-9]\+' -o
}

MESSAGE="$(cat $1)"
TICKET=$(parse_git_tracker_and_ticket)

if [ -n "$TICKET" ]
then
  if [[ $MESSAGE != "$TICKET "* ]]; then
    echo "$TICKET $MESSAGE" > $1
  fi
fi
# echo $(curl -s https://whatthecommit.com/ | grep "<p>" | sed "s/<p>//") > $1
