---
- name: Check if ctags is installed
  command: "ctags --version"
  ignore_errors: true
  register: ctags_check
  changed_when: false

- name: clone ctags
  git:
    repo: https://github.com/universal-ctags/ctags.git
    dest: "{{ ansible_env.HOME }}/tools/ctags"
    accept_hostkey: yes
    force: yes
  ignore_errors: yes
  when: ctags_check.rc != 0

- name: update & install ctags
  shell: cd {{ ansible_env.HOME }}/tools/ctags/ && git pull && ./autogen.sh && ./configure && make && sudo make install
