---

- name: Create ftplugin dir
  file:
    path: "{{ neovim_config_dir }}/after/ftplugin"
    state: directory

- name: Link ftplugin files
  file:
    src: "{{ item }}"
    dest: "{{ neovim_config_dir }}/after/ftplugin/{{ item | basename }}"
    state: link
  with_fileglob:
    - ftplugin/*
