---
- name: check rbenv version
  shell: rbenv -v || /bin/true
  register: rbenv_version_check

- block:
  - name: ruby deps
    become: yes
    package: name={{ item }} state=present
    with_items:
      - libssl-dev
      - libreadline-dev
      - zlib1g-dev

  - name: checkout rbenv repo
    git: >
      repo=https://github.com/rbenv/rbenv.git
      dest={{ ansible_env.HOME }}/.rbenv
      version={{ rbenv_version }}
      accept_hostkey=yes
      force=yes
    ignore_errors: yes

  - name: create plugins directory
    file: state=directory path={{ ansible_env.HOME }}/.rbenv/plugins
    ignore_errors: yes

  - name: configure rbenv
    shell: cd ~/.rbenv && src/configure && make -C src && eval "$(rbenv init -)"

  - name: checkout rbenv ruby-build repo
    git: >
      repo=https://github.com/rbenv/ruby-build.git
      dest={{ ansible_env.HOME }}/.rbenv/plugins/ruby-build
      accept_hostkey=yes
      force=yes
    ignore_errors: yes

  when: "rbenv_version_check.stdout.find('rbenv ' ~ rbenv_version) == -1"

- name: install ruby {{ ruby_version }}
  shell: $SHELL -lc "{{ ansible_env.HOME }}/.rbenv/bin/rbenv install --skip-existing {{ ruby_version }} && {{ ansible_env.HOME }}/.rbenv/bin/rbenv global {{ ruby_version }}"
